### ISSUE TITLE
Integrate with chriskempson/base16-shell?

### ISSUE THREAD

**Issue by gpaulsen** [PlusMinus0/base16-darcula#1]
Hi.

  This is a great theme.  Any thought about possibly integrating with https://github.com/chriskempson/base16-shell?  I like the flexibility of or the entire base16-shell project, but I like this theme in particular.

**Comment by gpaulsen** [comment]
Moving to Konstantin Bulenkov (github.com/bulenkov/Darcula)'s version of this repo, as it looks like it's upstream from this fork.

**Comment by PlusMinus0** [comment]
No, this repository is an implementation of the base-16 schema based on the IntelliJ color scheme in the other repository. The reason, why I did not publish this yet to the base16 repository is that I don't know if color schemes can be copyrighted and I wanted to make sure by requesting to relicense the original repository under MIT.

Unfortunately, the other repository was already stale, when i opened the issue, so I don't expect any response. Maybe I'll read a little more into it again and see, if I create a merge request for base16.
